### ISSUE TITLE
Broken links to ecology lesson materials

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/datacarpentry.github.io#101]
The links to the ecology introduction to R and dplyr lessons gives 404 errors. This appears to be because those modules only exist as .Rmd files (no corresponding html files in the lesson repo). Cross-posting to website and lesson repos to try to get fast fix. 

Thanks!

**Comment by gvwilson** [comment]
Which links that are 404'ing? I'm on <http://www.datacarpentry.org/lessons/>, under "Ecology Workshop", and the following work for me:

Data Analysis and Visualization in R: Site <http://www.datacarpentry.org/R-ecology-lesson/>

All links to episodes under "Lessons:" on that page work for me as well.

**Comment by tracykteal** [comment]
I think I see that you meant https://github.com/datacarpentry/ecology-workshop/?

There were broken links there and I just fixed them.

Is that the page you meant?

**Comment by ErinBecker** [comment]
@tracykteal Thanks Tracy. Those weren't the links I meant, but I'm glad you found (and fixed!) them. Francois fixed the lesson links last night.
