### ISSUE TITLE
Update SC minutes

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/datacarpentry.github.io#103]
Last update to /minutes/ is from Sept. 2015.

**Comment by ErinBecker** [comment]
@tracykteal Are the October and November minutes available?

**Comment by weaverbel** [comment]
Shall I close this?

**Comment by maneesha** [comment]
@tracykteal  I'm going through some super old issues.  I don't think the history of Data Carpentry's governance is on the DC website anymore.  Do we want a section on DC's history or can we close this?

**Comment by tracykteal** [comment]
Thanks, we can close this. I'll go ahead and do that.
