### ISSUE TITLE
Add partners page

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/datacarpentry.github.io#104]
Similar to http://software-carpentry.org/scf/partners/

**Comment by ErinBecker** [comment]
@weaverbel - Would be nice to have something like this on the joint Carpentries page, since memberships will be joint across the Carpentries. I'll make a task in Asana for this for the joint page and close this issue.

**Comment by tracykteal** [comment]
We'll be planning the joint website out in early 2018. Good to start documenting things we'll want to include.
