### ISSUE TITLE
Datacarpentry.com redirect

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/datacarpentry.github.io#107]
Datacarpentry.com currently redirects to software-carpentry.org. Tested in Chrome, Firefox and Safari. Weird. 

@gvwilson @tracykteal @jduckles Any idea how to fix this?

**Comment by weaverbel** [comment]
Assigned to me but I don't know how this could be done? Can anyone help? @jduckles ? @fmichonneau ?

**Comment by jduckles** [comment]
Should be fixed, please close if you see it working. Will take some time for the DNS to propagate.

**Comment by ErinBecker** [comment]
Thanks @jduckles. Works now.
