### ISSUE TITLE
For Instructors category 'Workshop checklists'

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/datacarpentry.github.io#124]
When talking about the checklists, it wasn't totally obvious where to find them. What about in the 'For Instructors' tab, adding a 'Workshop checklists' category that goes to a page with the checklists.

**Comment by ErinBecker** [comment]
There's currently a tab called "self-organized workshops" that goes to the homepage for self-org workshops. The checklist links are at the top of that page.

**Comment by ErinBecker** [comment]
Closed with [PR #127](https://github.com/datacarpentry/datacarpentry.github.io/pull/127)

**Comment by ErinBecker** [comment]
Updated with PR #131
