### ISSUE TITLE
No Data visualization in R lesson

### ISSUE THREAD

**Issue by rgaiacs** [datacarpentry/datacarpentry.github.io#133]
At http://www.datacarpentry.org/lessons/ we have

> Genomics Workshop
> Lessons
> Lesson    Site    Repository  Maintainer(s)
> Introduction to the workshop and dataset          Tracy Teal
> Introduction to cloud computing for genomics          Bob Freeman
> Introduction to the command line          Sheldon McKay, Karen Cranston
> Data wrangling and processing         Sheldon McKay, Karen Cranston
> Data analysis in R            Naupaka Zimmerman, Jason Williams
> Data visualization in R           Meeta Mistry

The "Data anlysis in R" and "Data visualization in R" link to the same lesson. We probably want to drop the "Data visualisation in R".

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/datacarpentry.github.io/commit/e17ee4e3721654db8dee9cc14a106df2e802aae4
