### ISSUE TITLE
Remove wood background on mobile view

### ISSUE THREAD

**Issue by rgaiacs** [datacarpentry/datacarpentry.github.io#137]
On mobile devices we have the wood background but not the logo.

![screenshot_2016-09-18_12-19-15](https://cloud.githubusercontent.com/assets/1506457/18615284/9412c46c-7d9a-11e6-98c1-a6e9a1223fd0.png)

**Comment by maneesha** [comment]
Catching up on a bunch of old issues!
I don't know how to fix this.  @rgaiacs  do you?
Maybe @fmichonneau ?  If anyone can share some info with me I can look into things more.  I don't even know where to start!

**Comment by maneesha** [comment]
Closing as stale
