### ISSUE TITLE
Add small padding on mobile devices

### ISSUE THREAD

**Issue by rgaiacs** [datacarpentry/datacarpentry.github.io#138]
because the text is close to the border of the device.

![screenshot_2016-09-18_12-19-15](https://cloud.githubusercontent.com/assets/1506457/18615289/b70421e6-7d9a-11e6-8f6d-0364a027fedd.png)

**Comment by maneesha** [comment]
Same as #137...

Catching up on a bunch of old issues!
I don't know how to fix this. @rgaiacs do you?
Maybe @fmichonneau ? If anyone can share some info with me I can look into things more. I don't even know where to start!

**Comment by maneesha** [comment]
Closing as stale
