### ISSUE TITLE
TOC genomics workshop inconsistent

### ISSUE THREAD

**Issue by lexnederbragt** [datacarpentry/datacarpentry.github.io#140]
At http://www.datacarpentry.org/lessons/#genomics-workshop, there is a link to the 'More workshop details' page (http://www.datacarpentry.org/genomics-workshop), and a table with direct links to lesson website pages. However:
- http://www.datacarpentry.org/genomics-workshop/ has links to Module 2: Data tidiness which are not in the table at http://www.datacarpentry.org/lessons/#genomics-workshop
- Introduction to cloud computing for genomics links to https://github.com/datacarpentry/cloud-genomics/tree/gh-pages/lessons from http://www.datacarpentry.org/lessons/#genomics-workshop, but to https://jasonjwilliamsny.github.io/cloud-genomics/ from http://www.datacarpentry.org/genomics-workshop
- Introduction to the command line   links to https://github.com/datacarpentry/shell-genomics/tree/gh-pages/lessons or http://www.datacarpentry.org/shell-genomics/lessons/
- other links I won't even try to figure out.

I was going to add links to these to the instructor training website, but I'll have to put this lesson on hold for a bit...

**Comment by ErinBecker** [comment]
Thanks @lexnederbragt  - these links were a bit of a mess for a while but are consistent now. Link structure will also be simplified with merge of https://github.com/datacarpentry/genomics-workshop/pull/29. Closing issue here.
