### ISSUE TITLE
Box size in layout is different on some pages

### ISSUE THREAD

**Issue by rgaiacs** [datacarpentry/datacarpentry.github.io#143]
Screenshot from http://www.datacarpentry.org/mission/

![screenshot_2016-10-12_11-36-18](https://cloud.githubusercontent.com/assets/1506457/19307051/69bb6c76-9070-11e6-835a-4036593f9b6e.png)

Screenshot from http://www.datacarpentry.org/media/

![screenshot_2016-10-12_11-36-01](https://cloud.githubusercontent.com/assets/1506457/19307047/65454cc0-9070-11e6-8be9-75ed443f3412.png)

Something on https://raw.githubusercontent.com/datacarpentry/datacarpentry.github.io/master/pages/about.md and https://raw.githubusercontent.com/datacarpentry/datacarpentry.github.io/master/pages/media.md is creating the difference on the layout.

**Comment by ErinBecker** [comment]
@rgaiacs There are two layout definitions "page" and "page-fullwidth". Some of the pages are set to "page" (the narrow version), while most are set to full-width. Personally, I think the pages with a lot of short lines (e.g. lists as in media, governance) look better with the narrow format. I'm open to changing all to be wide if there's a strong preference.

**Comment by maneesha** [comment]
Same as #137...

Catching up on a bunch of old issues!
I don't know how to fix this. @rgaiacs do you?
Maybe @fmichonneau ? If anyone can share some info with me I can look into things more. I don't even know where to start!

**Comment by maneesha** [comment]
Same as #137...

Catching up on a bunch of old issues!
I don't know how to fix this. @rgaiacs do you?
Maybe @fmichonneau ? If anyone can share some info with me I can look into things more. I don't even know where to start!

**Comment by maneesha** [comment]
Closing as stale
