### ISSUE TITLE
Change support to sponsors?

### ISSUE THREAD

**Issue by karthik** [datacarpentry/datacarpentry.github.io#15]
In the navbar, the word "support" reads weirdly to me (I think customer support, or just "help") but really it means financial support. Sponsors would be less ambiguous. At first I thought it was a mistake and that you forgot to change it from the default navbar item.

**Comment by tracykteal** [comment]
I originally had it as sponsor but changed it to support because I thought it was more all-encompassing. I see your point though and changed it back. Addressed in https://github.com/datacarpentry/datacarpentry.github.io/pull/17
