### ISSUE TITLE
assessment report on blog post still linked to Google doc rather than pdf

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/datacarpentry.github.io#160]
Did we want to link to the pdf rather than the Google doc? 

@ErinBecker @kariljordan

**Comment by kariljordan** [comment]
Yes, I sent it to Erin for the blog.

**Comment by ErinBecker** [comment]
Ugh - I thought I changed this. Just a minute.

**Comment by tracykteal** [comment]
Thanks @ErinBecker I see it's fixed.
