### ISSUE TITLE
enable https

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/datacarpentry.github.io#171]
https://datacarpentry.org should work.

An easy solution is to use https://cloudflare.com and set up a rule to redirect all traffic through https:

https://support.cloudflare.com/hc/en-us/articles/200170536-How-do-I-redirect-all-visitors-to-HTTPS-SSL-

**Comment by remram44** [comment]
GitHub now supports this, it should be enabled: https://blog.github.com/changelog/2018-05-01-costum-domains-for-gh-pages/

**Comment by fmichonneau** [comment]
@jduckles could you please set up the datacarpentry domain the same way as it's done for software-carpentry so we can take advantage of the CDN + https?

**Comment by tracykteal** [comment]
I have things set up, so have to move things over, so @jduckles has been waiting on me. datacarpentry.github.io redirects to datacarpentry.org so I want to make sure that will all work too.

**Comment by tracykteal** [comment]
Ah, ha, I see, I maybe don't need to move things over with this update, since it's supported with github. Thanks @remram44! Let me try this out.

**Comment by tracykteal** [comment]
I see how to do this. I need to update the A records, so I'll do this tonight, rather than now when people might be using the lessons, so that in case something goes wrong, I don't take them down.

**Comment by jduckles** [comment]
@tracykteal  This needs to happen before July arrives or you'll users will be getting "Not Secure" messages.

**Comment by tracykteal** [comment]
I've changed the settings on the nameserver. Just waiting for it to percolate to flip the HTTPS switch on github.

**Comment by fmichonneau** [comment]
all done!
