### ISSUE TITLE
Set up site to load as datacarpentry.org

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/datacarpentry.github.io#21]

**Comment by tracykteal** [comment]
yes, can you do that, or do I have to do that on my server? I just put in a redirect, but it would be better to update the DNS.

**Comment by ethanwhite** [comment]
Either way. I can do it by transferring the DNS back to Namecheap (i.e., my control) and then doing the setup to make it run properly with Github pages, or you can do the same thing from your DNS. Just let me know what you'd prefer.

**Comment by ethanwhite** [comment]
As discussed off line this needs to go through @tracykteal and will be handled when there are no actively running workshops.

**Comment by brymz** [comment]
The /semester-biology/ website is down at both http://www.datacarpentry.org/semester-biology/ and http://datacarpentry.github.io/semester-biology/. The response from Firefox to the url entry is "Problem loading page: The page isn't redirecting properly". I think this might be a problem across all of the datacarpentry repos.

**Comment by ethanwhite** [comment]
It's working fine for me at the moment. I wonder if the DNS changes haven't
all made it to your network yet. Can you retry in a few hours and report
back?

**Comment by brymz** [comment]
> Can you retry in a few hours and report back?

Sure thing.

**Comment by tracykteal** [comment]
Safari tends to not update well so you might have to restart that browser.

**Comment by brymz** [comment]
Restarting the browser did not work. I'll check back again in a couple of
hours.

**Comment by tracykteal** [comment]
Ok thanks. It's working for me from mobile.

**Comment by brymz** [comment]
After restarting the computer, both links work!

**Comment by ethanwhite** [comment]
Thanks @brymz. I'm going to go ahead and close this since the transition has been made and everything seems to be working.
