### ISSUE TITLE
Extra code in HTML 

### ISSUE THREAD

**Issue by rgaiacs** [datacarpentry/datacarpentry.github.io#268]
At http://www.datacarpentry.org/workshops-host/ you have

![screenshot from 2017-08-08 10-23-23](https://user-images.githubusercontent.com/1506457/29065430-f4d60efc-7c23-11e7-846d-18d3c97bfd6a.png)

**Comment by tracykteal** [comment]
Thanks! Fixed by https://github.com/datacarpentry/datacarpentry.github.io/pull/270

**Comment by rgaiacs** [comment]
I'm closing this based on the previous comment.
