### ISSUE TITLE
Request for Comment: Share your thoughts on the future of The Carpentries blog post is missing

### ISSUE THREAD

**Issue by rgaiacs** [datacarpentry/datacarpentry.github.io#295]
https://software-carpentry.org/blog/2017/09/rfc.html

**Comment by weaverbel** [comment]
Post is up now @rgaiacs - should I close this?

**Comment by rgaiacs** [comment]
> Post is up now

Are you sure?

I can't find the cross post at http://www.datacarpentry.org/blog/. It is on the Software Carpentry blog but it also should be on the Data Carpentry one.

**Comment by weaverbel** [comment]
It is here: http://www.datacarpentry.org/blog/lat-am-lessons/

**Comment by rgaiacs** [comment]
@weaverbel The link that you sent is for the Latin America. The one that I open the issue is about the merge.

**Comment by tracykteal** [comment]
Thanks @rgaiacs you're right, and thanks for pointing this out. I put in a PR on the datacarpentry website https://github.com/datacarpentry/datacarpentry.github.io/pull/297

**Comment by tracykteal** [comment]
Posted now on datacarpentry.org, so closing.
