### ISSUE TITLE
Fix issues with "Our long-term assessment results are in!" blog post

### ISSUE THREAD

**Issue by kariljordan** [datacarpentry/datacarpentry.github.io#306]
@rgaiacs Do the issues you found [here](https://github.com/swcarpentry/website/pull/852) apply to [this post](https://github.com/datacarpentry/datacarpentry.github.io/blob/master/_posts/2017-10-18-long-term-survey-results.md)

**Comment by rgaiacs** [comment]
You probably want https://github.com/swcarpentry/website/pull/852/commits/b385f1acd77425800ece7ee8cb8ea990079e4ce8.

You don't need https://github.com/swcarpentry/website/pull/852/commits/7ec15b082b25356fa0015bc5e9f11ce038884393. See https://github.com/swcarpentry/website/issues/853 for a long explanation.

Don't apply https://github.com/swcarpentry/website/pull/852/commits/9a43e896898c5cac35e13f8beba3a3c4b181aec9. It will have side effects.

You can apply a modified version of https://github.com/swcarpentry/website/pull/852/commits/86a1db1bb9f0bf398e275421f6fcb5ecc7794531 if you want. This one is more a mater of preference. If the content that you are linking is removed the blog doesn't change.

**Comment by kariljordan** [comment]
I went through each of your suggestions and it didn't look as if I needed to change anything. Any way to get the figures to look smaller? They're taking up so much space.
