### ISSUE TITLE
workshops page out of date

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/datacarpentry.github.io#329]
Workshops page lists current curriculum, but the lessons page has been updated with curricula in progress. Would be good to simplify this page to just link to the lessons page and then the "attend a workshop/ request a workshop / organize a workshop" buttons.

**Comment by yetiracing4als** [comment]
Simplifying the page would help, and I will work on changing the code and submitting the suggestions below:

A Data Carpentry workshop teaches the core skills for working with data effectively and reproducibly.  Each workshop is developed to provide a learner fundamental skills around a specified domain.  These skills are taught in a two-day, hands-on forum and are designed for learners with little to no prior computational experience.  Being domain specific, though, they allow researchers to work with data most relevant to their own subject material. 

Data Carpentry workshops must include:
A Data Carpentry lesson on data organization
Three other modules in the same domain from the Data Carpentry curriculum

(as buttons) Request a workshop | Attend a workshop | Organize a workshop

**Comment by maneesha** [comment]
Closed just like #451
