### ISSUE TITLE
Current Steering Committee Members is out of date

### ISSUE THREAD

**Issue by rgaiacs** [datacarpentry/datacarpentry.github.io#381]
Current Steering Committee Members in http://www.datacarpentry.org/people/ might need to be updated as mentioned in http://www.datacarpentry.org/blog/datacarpentry-looking-forward-looking-back/.

**Comment by weaverbel** [comment]
I am happy to update if you can point me to the list of people I should include @tracykteal or @ErinBecker

**Comment by maneesha** [comment]
http://www.datacarpentry.org/people/ now redirects to The Carpentries staff page (https://carpentries.org/team/).
Closing this.
