### ISSUE TITLE
Broken link to Data Carpentry teaching practices 

### ISSUE THREAD

**Issue by alex-konovalov** [datacarpentry/datacarpentry.github.io#400]
Reported by one of Instructor Training workshop participants: https://github.com/datacarpentry/datacarpentry.github.io/blob/master/pages/instructor-checklist.md has broken link to Data Carpentry teaching practices (http://carpentries.github.io/instructor-training/15-practices/).

**Comment by tracykteal** [comment]
Thanks for pointing this out. Just put in a PR to fix.
