### ISSUE TITLE
Adding the Open Refine download link

### ISSUE THREAD

**Issue by celinergb** [datacarpentry/datacarpentry.github.io#429]
We direct participants to simply Open Refine's home page (http://openrefine.org/) in the setup (http://www.datacarpentry.org/OpenRefine-ecology-lesson/setup/). For absolute beginners it may be better to actually post the link to the download page (http://openrefine.org/download.html). Although this is a small step to take, this may help cut down on cognitive load that some novices experience at the beginning of a workshop.

**Comment by fmichonneau** [comment]
transferred to  openrefine lesson repo: https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues/185
