### ISSUE TITLE
Pyplot tutorial should close plots

### ISSUE THREAD

**Issue by crocodoyle** [datacarpentry/datacarpentry.github.io#430]
In lesson 7, (http://www.datacarpentry.org/python-ecology-lesson/07-putting-it-all-together/), none of the examples close pyplot. This isn't a problem if only following the examples, but very important if you're creating figures in loops or creating lots of plots.

**Comment by fmichonneau** [comment]
closing in favor of datacarpentry/python-ecology-lesson#277
