### ISSUE TITLE
lesson links in menu not working

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/datacarpentry.github.io#436]
The links to the sections for individual curricula in the lessons menu aren't working. I just added those in a recent PR (https://github.com/datacarpentry/datacarpentry.github.io/pull/435) and the hrefs appear to be correct. Not sure what's wrong. @tracykteal @fmichonneau any ideas?

**Comment by maneesha** [comment]
With html anchors you can't have a trailing `\`
So http://www.datacarpentry.org/lessons/#genomics-workshop will work but http://www.datacarpentry.org/lessons/#genomics-workshop/ will not

**Comment by ErinBecker** [comment]
Thanks @maneesha!!! I'll fix that right now.
