### ISSUE TITLE
List of blog posts is out of date

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/datacarpentry.github.io#441]
Blog posts displayed on front page of website are from April 2018.  Most recent blog post from May 2018 on social sciences does not show up on the front page.  It is on the archive page (http://www.datacarpentry.org/blog/archive/).

**Comment by fmichonneau** [comment]
This is a feature of our current template, the latest blog post is listed before the 3 pictures on the front page, and the following ones are listed below under "Blog posts". All the posts are being displayed as far as I can tell. Closing, but @maneesha feel free to open a separate issue if you think that we can improve how the list of recent blog posts are being organized.
