### ISSUE TITLE
DC sponsors page needs updating

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/datacarpentry.github.io#447]
The [sponsors page](http://www.datacarpentry.org/sponsors/) lists DC as a project of NumFOCUS.  It also refers to itself as "a spin-off organization of Software Carpentry".

**Comment by weaverbel** [comment]
Fix is in but merge keeps failing - have escalated to @fmichonneau to fix https://github.com/datacarpentry/datacarpentry.github.io/pull/455
