### ISSUE TITLE
use template variables for things like contact info

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/datacarpentry.github.io#450]
I've just put in a bunch of PRs to update the contact emails to team@carpentries.org.
On the SWC website,  data like contact email addresses are managed through template variables so we don't have to make updates across the board.  Can the DC website be set up similarly?

**Comment by fmichonneau** [comment]
I just created the `dc_email` global variable set to team@carpentries.org, so something like this will work:

```
[contact us](mailto:{{ site.dc_email }})
```

**Comment by weaverbel** [comment]
So is this done? Can this be closed? @maneesha @fmichonneau

**Comment by maneesha** [comment]
I'll defer to @fmichonneau 
He just created the variable but it's not in use anywhere yet.  What's the easiest way to replace all email addresses on the website with the new variable?

**Comment by maneesha** [comment]
Assigning to myself to search the repo and make all mailto links go to `(mailto:{{ site.dc_email }})`

**Comment by maneesha** [comment]
#495 takes care of this for the team@carpentries.org email address.  Leaving this issue open to consider other places we should be using variables rather than hard coding email addresses and such.
