### ISSUE TITLE
DC workshops page needs updating

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/datacarpentry.github.io#451]
The  curricula we offer listed here is out of date:

http://www.datacarpentry.org/workshops/

**Comment by weaverbel** [comment]
Pinging @ErinBecker @fmichonneau - what do you want to list here?

**Comment by fmichonneau** [comment]
I suggest we remove the list of workshops from here and point to the "lessons" page instead that we try to keep up to date

**Comment by maneesha** [comment]
I think we should take this page down entirely and have it redirect to https://datacarpentry.org/lessons/

**Comment by ErinBecker** [comment]
I agree with @fmichonneau and @maneesha

**Comment by maneesha** [comment]
Catching up on old issues.  @fmichonneau  Would you be able to set up this redirect?

**Comment by fmichonneau** [comment]
I think this page is useful. We can remove the last part "Data Carpentry workshops must include:...".

If we take down this page and redirect to the lesson page, then the "Workshop" menu doesn't have a description of what our workshops are, and visitors would be driven away from the other pages about workshops (request, attend, host a workshop).

**Comment by tracykteal** [comment]
I also think this page is useful. We need to have somewhere the 'Data Carpentry workshops must include'. We can use this page as a place to talk about the concept of DC workshops. What distinguishes them from SWC or LC for instance. 

Agree it needs updating though, especially to sync up with the new Carpentries workshop page. http://static.carpentries.org/workshops/

This page could help you get more information on if a DC workshop is right for you.

Ideas of what should be on this page:
- Who is the DC audience. Maybe 'Who should attend?'
- Goals of DC workshops
- About the narrative approach
- About the data that we use in DC workshops
- What must be included to call it a DC workshop

other things?

**Comment by maneesha** [comment]
Closing this for now; will open another issue about how workshops are managed across all four websites.
