### ISSUE TITLE
Greg's title needs to be updated

### ISSUE THREAD

**Issue by hlapp** [datacarpentry/datacarpentry.github.io#47]
He's listed as ED of Software Carpentry, which presumably he isn't anymore?

**Comment by gvwilson** [comment]
It's true, I'm not - don't actually know what my job title is these days...

**Comment by tracykteal** [comment]
Good point. It is actually important to update it, since Jonah officially has that role. Perhaps you could ask the SCF SC what your title is? Could you just be the Associate Director? Let me know or put in a PR when you find out.

**Comment by ErinBecker** [comment]
@tracykteal @gvwilson Greg's title on /people/ is currently "Co-Founder and Director of Training, Software Carpentry Foundation". Can I close this issue or is there somewhere else it needs to be changed?
