### ISSUE TITLE
DC website list of workshops inaccurate

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/datacarpentry.github.io#473]
The list of workshops on the website doesn't seem to be pulling workshops from AMY properly.
It lists out of date workshops - today, Dec 5, there are workshops from Dec 3-4 listed.

It also lists SWC workshops - does not limit the listing to DC workshops.

Seems like this issue has come up often before: https://github.com/datacarpentry/datacarpentry.github.io/issues/416

Tagging @tracykteal @jduckles @fmichonneau @ErinBecker

**Comment by fmichonneau** [comment]
The list of workshops was last pulled 18 hours ago when it was December 4th so it's why it's still showing workshops from Dec 3-4. When it runs again in about 6 hours, these workshops shouldn't be listed.

While Travis runs every 24 hours we can't quite control the time of day it's running, and with time zones, I don't think we can work around this very easily.

**Comment by maneesha** [comment]
Thanks @fmichonneau - I'll check back on the Dec 3-4 workshops later.

It is also showing SWC workshops when it should be limited to DC workshops.

**Comment by tracykteal** [comment]
SWC is also showing non SWC workshops, for instance the George Mason University workshop is Library Carpentry. Library Carpentry workshops look right though.

**Comment by tracykteal** [comment]
Looking back through _data/amy.json it seems like this could have been happening for a bit.

**Comment by fmichonneau** [comment]
I'll try to look into it soon but this is probably related to https://github.com/carpentries/amy-feeds/issues/4

**Comment by tracykteal** [comment]
That was my thought too. I just couldn't track down why it was working for LC and not the others.

**Comment by maneesha** [comment]
@fmichonneau  is there an update on this?

**Comment by maneesha** [comment]
Checking in - is there anything I can do to help fix this?  We've been getting emails as this is causing confusion.  @fmichonneau @tracykteal 

(Note that @libcce  manually curates the LC list)

**Comment by fmichonneau** [comment]
This [python script](https://github.com/carpentries/amy-feeds/blob/master/bin/get-amy.py) needs to be edited to take into account the changes in the AMY API described [here](https://github.com/swcarpentry/amy/pull/1363#issuecomment-427594814). If it's something you think you could tackle that would be great. I'm happy to test and review

**Comment by fmichonneau** [comment]
switched data source to use redash query instead of directly querying the AMY API. The list should now be accurate.
