### ISSUE TITLE
Difference between "workshop" and "curriculum"

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/datacarpentry.github.io#488]
In the page section headings, we refer to our offerings as:

* Ecology Curriculum
* Genomics Curriculum
* Social Science Curriculum
* Geospatial Data Workshop (but "Geospatial data curriculum" in TOC at top of page)

Higher level headings refer to everything as *Workshop Materials*

Is there an intended difference in using the term *workshop* vs the term *curriculum*?  If not can I change *Geospatial Data Workshop* to *Geospatial Data Curriculum*?  What about changing *Workshop Materials* to *Curriculum Materials* to keep language consistent?

**Comment by ErinBecker** [comment]
Good catch @maneesha. Please change to curriculum.
