### ISSUE TITLE
404 on new blog post

### ISSUE THREAD

**Issue by brainwane** [datacarpentry/datacarpentry.github.io#49]
http://www.datacarpentry.org/blog/associate-director-posting/ is linked to from the front page but gives a 404 error.

**Comment by hlapp** [comment]
Actually all blog links from the front page stopped working. Not sure what's going on.

**Comment by tracykteal** [comment]
This is strange. It's a redirect issue somehow. Nothing has changed on the site since it was working before though. Maybe a github change? I'm looking in to it.

**Comment by tracykteal** [comment]
Fixed. We had an old repo called 'blog'. Github settings must have changed so that was the default wwww.datacarpentry.org/blog/ Since I had already moved those posts over to our new website, I just deleted the 'blog' repo and things work fine now.

**Comment by tracykteal** [comment]
Thanks for quickly pointing this out!
