### ISSUE TITLE
The Carpentries Tagathon - Suggest Relevant Tags for Blog Posts

### ISSUE THREAD

**Issue by serahrono** [datacarpentry/datacarpentry.github.io#499]
October 28  to November 1 2019 is The Carpentries Tagathon week. This means we will be working to add relevant tags to as many posts as possible on the [Data Carpentry](https://datacarpentry.org/blog), [Library Carpentry](https://librarycarpentry.org/blog) and [Software Carpentry](https://software-carpentry.org/blog) blogs. More information about this initiative is available [in this blog post](https://carpentries.org/blog/2019/10/carpentries-tagathon/).

You can contribute to this initiative by reading the posts on any of the three blogs, and suggesting between one and three tags that should be added to the posts. 

The Carpentries Handbook has [a detailed guide on adding tags to blog posts](https://docs.carpentries.org/topic_folders/communications/guides/select-blog-tags.html) published across all  our blogs. 

All Pull Requests associated with the Tagathon and touching on any of the 173 Data Carpentry blog posts will reference this issue, so you can keep track of them below. 

---

Interested in suggesting tags for posts in Library Carpentry and Software Carpentry blogs too? See what others have worked on under the
* [Carpentries Tagathon issue](https://github.com/LibraryCarpentry/librarycarpentry.github.io/issues/73) on the Library Carpentry repository
* [Carpentries Tagathon issue](https://github.com/swcarpentry/website/issues/1086) on the Software Carpentry repository
and start contributing.

**Comment by serahrono** [comment]
addresses #494

**Comment by maneesha** [comment]
@kmomar @acrall We have a number of issues about tags on blog post that have been open for up to two years. Do you want to keep these open?

**Comment by kmomar** [comment]
@maneesha @acrall we are closing this issue as it is open-ended and can't be addressed and hasn't seen activity since 2019
