### ISSUE TITLE
Test content in blog post

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/datacarpentry.github.io#515]
@fmichonneau  @ErinBecker  
Was this post supposed to have actual content in it? Otherwise we should remove it.

Post:  https://datacarpentry.org/blog/2018/05/test
File on Github: https://github.com/datacarpentry/datacarpentry.github.io/blob/master/_posts/2018-05-21-test.md

**Comment by ErinBecker** [comment]
Thanks weird. I don't remember that at all. Yes, please delete. Thanks for catching this @maneesha

**Comment by maneesha** [comment]
Fixed with https://github.com/datacarpentry/datacarpentry.github.io/commit/c62cc9bc7e508d6518a85c7bdbbf2d8ee6dcbbee
