### ISSUE TITLE
Blog post not showing up

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/datacarpentry.github.io#516]
On the [front page](https://datacarpentry.org/) of the Data Carpentry site, [this blog post](https://github.com/datacarpentry/datacarpentry.github.io/blob/master/_posts/2019-05-15-genomics-pilot.md) does not show up.  It does show up if you go to the [blog archive page](https://datacarpentry.org/blog/archive/).

I remember fixing something like this before - @fmichonneau if you remember what we did, feel free to put in a fix.  Otherwise I'll look into it more in a bit.

**Comment by fmichonneau** [comment]
this actually comes from the template. Normally the latest blog post is displayed somewhere else and then older posts are in the list. It looks like at some point we removed showing the latest blog post without changing the list. I'll put a fix in.
