### ISSUE TITLE
Link to "Image analysis curriculum" not working

### ISSUE THREAD

**Issue by snownontrace** [datacarpentry/datacarpentry.github.io#518]
On the Data Carpentry lessons website (https://datacarpentry.org/lessons/#other-curriculum), the link to "Image analysis curriculum" under "Curriculum materials under development or consideration" is not working, while links to other curriculums will take the reader to the information paragraph below, which further links to the material in development.

**Comment by ErinBecker** [comment]
Thanks for the issue @snownontrace! This should be solved with https://github.com/datacarpentry/datacarpentry.github.io/pull/517, but I'll confirm in the live render before closing.

**Comment by ErinBecker** [comment]
Fixed! thanks again @snownontrace :-)
