### ISSUE TITLE
Redirect workshops page to Carpentries site?

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/datacarpentry.github.io#521]
Right now we have [this workshops page](https://datacarpentry.org/workshops-host/) on the DC site, that contains much of the same information as [The Carpentries workshops page](https://static.carpentries.org/workshops/).  I'd like to deprecate the page on the DC site and redirect it to The Carpentries workshop page.

@sheraaronhurt  let me know what you think.

**Comment by sheraaronhurt** [comment]
Love the idea @maneesha ! This will ensure that all LP are providing the same message.
