### ISSUE TITLE
add past workshops page

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/datacarpentry.github.io#54]
It would be great to have a past workshops page like SWC has. 

http://software-carpentry.org/workshops/past/

**Comment by tracykteal** [comment]
I added a past workshop page. 
http://www.datacarpentry.org/workshops-past/

It doesn't have the map, so that can still be added, so I'll keep this issue open.

**Comment by ErinBecker** [comment]
@weaverbel - Do you think this is something you could implement? It would be nice to have the map like SWC has. Not a time rush, but would be good at implement this at some point. Please let me know what you think.

**Comment by tracykteal** [comment]
I'll close this here, as I think now we'd put all our workshops on one map on carpentries.org
