### ISSUE TITLE
Links to Lesson Instructor Guides

### ISSUE THREAD

**Issue by tobyhodges** [datacarpentry/datacarpentry.github.io#542]
The discussion on https://github.com/datacarpentry/datacarpentry.github.io/pull/531 caused me to do a sweep for broken links from https://datacarpentry.org/lessons/ to Reference and Instructor Notes pages for each lesson. This highlighted an apparent inconsistency between the Reference page links - which point to [lesson-url]/reference.html - and Instructor Notes page links - which are pointing to [lesson-url]/guide/.

None of [the boilerplate files in the lesson template](https://github.com/carpentries/styles/blob/gh-pages/bin/boilerplate/_extras/guide.md) specify a permalink in the YAML front matter, so by default I would expect the Instructor Notes page on a new lesson to have a URL in the form [lesson-url]/guide.html. That would mean a broken link from https://datacarpentry.org/lessons/ ...

I *think* the best way to tackle this is to remove the inconsistency on https://datacarpentry.org/lessons/ by pointing Instructor Notes links to [lesson-url]/guide.html and removing the permalink front matter on the relevant page of each lesson. I'm happy to take care of this, if @fmichonneau and @maneesha agree it's the right way to go?

**Comment by fmichonneau** [comment]
yes, that's the way to go, thanks for checking Toby.

**Comment by tobyhodges** [comment]
hmmm. looking at [`_config.yml` in the boilerplate of `styles`](https://github.com/carpentries/styles/blob/gh-pages/bin/boilerplate/_config.yml), the `_extras` and `_episodes` collections are setup to use `/:path/index.html`, meaning that, even if the permalink is not set in the YAML front matter of the page itself, the path to the page will still be `/whatever/index.html`. This means that removing the `permalink` fields from the front matter of the pages won't make any difference and the approach I proposed above won't work. Perhaps I should just leave it as-is for the time-being? I don't like the inconsistency between the URLs for the Reference page and the other Extras, but I also don't think it's worth changing the configuration of the whole lesson template to fix it...

**Comment by tobyhodges** [comment]
hmmm. looking at [`_config.yml` in the boilerplate of `styles`](https://github.com/carpentries/styles/blob/gh-pages/bin/boilerplate/_config.yml), the `_extras` and `_episodes` collections are setup to use `/:path/index.html`, meaning that, even if the permalink is not set in the YAML front matter of the page itself, the path to the page will still be `/whatever/index.html`. This means that removing the `permalink` fields from the front matter of the pages won't make any difference and the approach I proposed above won't work. Perhaps I should just leave it as-is for the time-being? I don't like the inconsistency between the URLs for the Reference page and the other Extras, but I also don't think it's worth changing the configuration of the whole lesson template to fix it...

**Comment by fmichonneau** [comment]
Sorry for the confusion Toby, I misread your initial comment. The URL pattern the template expects for these pages is `:path/index.html` as defined in the current version of the `_config.yml`. When the `permalink` variable is set in the header of pages, this takes precedence over what is defined in `_config.yml`. Therefore removing this variable from the Extras pages is the way to go and the rendered links will be `/guide/index.html`, `/reference/index.html`, etc.

**Comment by maneesha** [comment]
Checking in @tobyhodges  Are you still working through this?

**Comment by tobyhodges** [comment]
There are still several lessons I need to submit fixes to for this, so I'd like to leave it open. I'll add a checklist here as a way to track my progress.

- [x] swcarpentry/shell-novice
- [x] swcarpentry/python-novice-inflammation
- [x] swcarpentry/git-novice-es (PR pending approval)
- [ ] swcarpentry/python-novice-gapminder
- [ ] swcarpentry/r-novice-inflammation
- [ ] swcarpentry/r-novice-gapminder
- [ ] swcarpentry/shell-novice-es
- [ ] swcarpentry/r-novice-gapminder-es
- [ ] swcarpentry/make-novice
- [ ] swcarpentry/matlab-novice-inflammation
- [ ] datacarpentry/ecology-workshop
- [ ] datacarpentry/python-ecology-lesson
- [ ] datacarpentry/python-ecology-lesson-es
- [ ] datacarpentry/spreadsheets-socialsci
- [ ] datacarpentry/openrefine-socialsci
- [ ] datacarpentry/python-socialsci
- [ ] datacarpentry/sql-socialsci
- [ ] librarycarpentry/lc-data-intro
- [ ] librarycarpentry/lc-python-intro
- [ ] librarycarpentry/lc-data-intro-archives

So, seventeen still to go at time of writing. If I do one per day, you should be able to close this before December!

**Comment by tobyhodges** [comment]
Pull Requests have now been submitted to make these permalinks consistent across all official lessons, and most have been merged already. I'm going to close this Issue now but feel free to post here and reopen if you'd like to discuss further or if you notice there's still an issue.

**Comment by fmichonneau** [comment]
Thank you for all your work on this!
