### ISSUE TITLE
Menu items in top menu bar does not display correctly

### ISSUE THREAD

**Issue by chendaniely** [datacarpentry/datacarpentry.github.io#556]
I'm running Firefox 84.0.1 (64-bit) on Manjaro Linux using KDE
and the top menu bar for the data carpentry website does not toggle the navbar correctly as the browser window resizes horizontally.
This only happens on the DC website, not the SWC or LC websites.

when it's "narrow" (< 1027 pixels) the navbar correctly turns into the "hamburger" bar,
![image](https://user-images.githubusercontent.com/5782147/103560771-572bbb00-4e86-11eb-82ce-8f911d2dcc95.png)

However, between 1027 - 1217 (inclusive) the "Home" to "For Instructors" options disappear, only showing "Sponsors, Contact, Search".
edit: It actually does not disappear, the "Home" to "For Instructors" actually show on a second line that gets covered up by the banner photo.
![image](https://user-images.githubusercontent.com/5782147/103560800-66ab0400-4e86-11eb-81c3-97c1ff5d9501.png)

pixels >= 1218 wide it displays correctly.
![image](https://user-images.githubusercontent.com/5782147/103560824-79253d80-4e86-11eb-8b26-15f89b3a2e61.png)

**Comment by maneesha** [comment]
Thanks for catching this @chendaniely 
We'll look into updating [the theme](https://phlow.github.io/feeling-responsive/) this website uses to see if that fixes things.

**Comment by fmichonneau** [comment]
the problem comes from the fact that the template wasn't designed to include something other than "contact" and "search" on the right corner. By adding "sponsors", the responsiveness gets broken.

**Comment by maneesha** [comment]
Thanks for catching the problem @fmichonneau 

@serahrono  do you have suggestions from a communications perspective of how to handle this? We could keep it as is, or we could remove the "sponsors" option.  What do you think? I appreciate your feedback!

**Comment by maneesha** [comment]
Pinging @serahrono

**Comment by maneesha** [comment]
OK, I just tried to remove the "Sponsor" item from the right side of the tool bar and still get the same effect.
@fmichonneau  do you have any other suggestions as to what might cause this? 


![dc_menubar](https://user-images.githubusercontent.com/829690/115059791-08de7d00-9eb5-11eb-8e1d-b38d16911f5a.gif)

**Comment by sstevens2** [comment]
Ran into this issue myself today.  Thanks @chendaniely for your excellent issue description!  Mine wasn't going to be nearly as descriptive.

**Comment by maneesha** [comment]
Closing this as we have reduced our menu layout and are planning additional changes so this will become irrelevant.  Anyone can feel free to re-open or start a new issue if any other problems are revealed.
