### ISSUE TITLE
Where should "Self organized workshops" go to in DC menu? 

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/datacarpentry.github.io#613]
### What is the problem?

In the [DC website](https://datacarpentry.org/) menu for "For Instructors" there is an option for "Self organized workshops" that goes to the [host checklist in the handbook](https://docs.carpentries.org/topic_folders/hosts_instructors/hosts_instructors_checklist.html#host-checklist).  Is this where it should go? If not, where should it go instead? Or should the "Self Organized Workshops" menu item be removed entirely?

@sheraaronhurt  Let me know what you want to do and I will make the change.

**Comment by sheraaronhurt** [comment]
@maneesha  thanks for bringing this to my attention. That can be moved because the option above it "Workshop Checklist" takes them to the same place with more information.
