### ISSUE TITLE
Status of Genomics R lesson? (alpha or beta?) 

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/datacarpentry.github.io#633]
### What is the problem?

In the section for the [genomics lesson](https://datacarpentry.org/lessons/#genomics-workshop), the intro text says that the Genomics lesson for  data in R is in in "alpha" but the table below it says that it is in "beta."  

### Location of problem (optional)

https://datacarpentry.org/lessons/#genomics-workshop

**Comment by maneesha** [comment]
Checking in @tobyhodges

**Comment by tobyhodges** [comment]
Good catch, @maneesha. The introductory text should indeed be updated to say "beta".
