### ISSUE TITLE
Reorganize involved-instructor page

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/datacarpentry.github.io#70]
1) [Training course link](http://swcarpentry.github.io/training-course/) goes to MOOC page. This isn't used anymore, right? I suggest it go instead to [current curriculum](http://swcarpentry.github.io/instructor-training/).

2) With new partnerships model, no longer any opportunity for individuals not affiliated with partner institution to go through training, right? 
If that's correct:
- I can draft some language to communicate that here,
- we can add list of partner institutions and some info about how to sign up for training at their institution,

If not: 
- Is training still in backlog? If so - that needs to be more clearly communicated here. If not, let's post a list of upcoming training events.

3) The "two steps to becoming an instructor" is a bit misleading as it ignores the checkout process. We should add link to checkout instructions here.

I can take point on making some changes here, but want to make sure I fully understand where we're at with changes to training before I do.

**Comment by gvwilson** [comment]
On 2016-05-16 1:10 PM, Erin Becker wrote:

> 1) [Training course 
> link][http://swcarpentry.github.io/training-course/] goes to MOOC 
> page. This isn't used anymore, right? I suggest it go instead to 
> [current curriculum][http://swcarpentry.github.io/instructor-training/].
>

The training-course repo isn't used any more - I should delete it or 
mark it as deprecated.

**Comment by ErinBecker** [comment]
> The training-course repo isn't used any more - I should delete it or
mark it as deprecated.

Any objection to linking to the instructor training materials here? I think it would be great if instructors/trainees had access to those outside of their training session so they can use them as a reference. Not sure if they're currently shared that way.

**Comment by ErinBecker** [comment]
Related note - 

On the for-instructors page, can we add a form that links to upcoming workshops with an "I'm available to teach" link of some sort? Would be great if instructors had a way of easily letting us know that they could teach at a specific event. Or does this already exist somewhere?

**Comment by gvwilson** [comment]
Ping @maneesha

**Comment by ErinBecker** [comment]
Started branch (erinbecker-instructor) to work on edits to instructor related pages (involved-instructor and for-instructors).

Can someone clarify for me the issue about partnerships (#2 above)?

Also - for some annoying reason, numbered bullets are showing up sequentially (1,2) in preview mode, but as (1,1) after commit. Any tips? 

https://github.com/datacarpentry/datacarpentry.github.io/blob/erinbecker-instructor/pages/involved-instructor.md

**Comment by ErinBecker** [comment]
I don't know what "Complete a guided teaching practice for one Data Carpentry lesson" refers to on the involved-instructors page. I don't see this mentioned anywhere in the checkout rubric. Is this an old checkout requirement? If still used, where can I find more info?

**Comment by gvwilson** [comment]
The simplest thing would be to refer people to 
https://swcarpentry.github.io/instructor-training/checkout/ , which will 
always have the up-to-date explanation of the checkout procedure.
