### ISSUE TITLE
Make timeline for checkout process realistic

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/datacarpentry.github.io#85]
@tracykteal The current "become an instructor" text says that checkout process takes "a total of approximately 2 hours". Since the discussion session is an hour, we're saying that submitting a meaningful PR and prepping and then teaching a demo takes only an hour combined. 

Both of these tasks require instructors to get pretty familiar with a specific lesson, and this seems unrealistic to me to do in an hour (and it would actually be less than an hour, after subtracting time for the mechanics of teaching and submitting a PR). 

Initial estimates in the Instructor Development Process doc were closer to 8-10 hours for the whole checkout process, and this is probably more realistic. 

Ok with changing to 8-10 hours? Or leave off time estimate?

**Comment by gvwilson** [comment]
We can poll some recently-completed instructors to get times - I think 
an hour for discussion, an hour for demo, and 2-3 hours for the PR, so a 
total of 4-5, but I'm probably being optimistic about the PR time.

**Comment by ErinBecker** [comment]
Really only an hour for demo? I'm assuming the mechanics of that take about half an hour (5 minutes teaching, plus time for setup, feedback, etc). Do you think it only takes a new instructor half an hour to get comfortable enough with the material for a full lesson to be ready to teach any portion of it without warning? I'm skeptical. 

2-3 hrs for the PR sounds reasonable to me.

**Comment by gvwilson** [comment]
You're right, that should probably be 2 hours, maybe 3.  Want me to poll 
a couple of dozen recently-finished instructors to get their numbers?

**Comment by ErinBecker** [comment]
Wouldn't hurt. Or we could just take the time estimate off and recognize that it will take different people different amounts of time depending on their familiarity with the materials and whether they've done a PR before.

**Comment by gvwilson** [comment]
I'd like to have some kind of estimate, even if it's a range, because 
the question comes up (and I always like having some idea of what I'm 
getting myself into when I'm asked to do something).  I'll poll...
cheers,
G

**Comment by ErinBecker** [comment]
@gvwilson Any update on this?

**Comment by gvwilson** [comment]
Mail sent with data - one option would be to incorporate the figures 
themselves in the page (to encourage trainees to report theirs ongoing).

**Comment by ErinBecker** [comment]
Based on the data, I'm comfortable stating range as ~8-10 hours. Only a few people went substantially over that, so I think this would serve the goal of helping people plan their time and know what they're committing to.

**Comment by ErinBecker** [comment]
Changed to "approximately 8-10 hours". Thanks for the help and data collection @gvwilson!

**Comment by ErinBecker** [comment]
@gvwilson Just an FYI that the SWC website doesn't have a time estimate - in case you wanted to add.
