### ISSUE TITLE
Awkward blog navigation

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/datacarpentry.github.io#88]
- [x] Have blog entry open upon initial title click (rather than having to click "read more")
- [x] Add author and date tags to blog post template
- [x] Enable navigation to previous and next blog posts from within individual posts

1 - may have been a strategic choice - I think it's a bit awkward and wonder whether we actually have any users are going to read the "teaser" and then decide not to click through to the article. This seems like the only reason to have it set up this way.

2 - Currently impossible to tell when blog posts were published, which makes it hard/impossible to understand historical context of posts.

3 - Not being able to click between posts makes it less likely people will read multiple posts.

**Comment by ErinBecker** [comment]
@tracykteal Let me know if there are any objections to these changes. I can take care of mechanics.

**Comment by tracykteal** [comment]
It's mainly set up this way, because these are the default mechanics. It takes a bit of digging to do things differently. 

These are good suggested changes, so you would be welcome to work on it.

**Comment by ErinBecker** [comment]
Made blog home more condensed with #128

**Comment by tracykteal** [comment]
Looks better, thanks!

**Comment by ErinBecker** [comment]
Thanks, still working on a few other aesthetics. Figuring out what controls what on the blog is fairly convoluted. . .

**Comment by ErinBecker** [comment]
Enabled navigation between blog posts with PR #129. Buttons currently only "Next and Previous", would like to be post titles and to be centered. Leaving open.
