### ISSUE TITLE
Self-organized workshop form

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/datacarpentry.github.io#90]
@maneesha The "request a self-organized workshop" form that links off of /self-organized-workshops/ includes several questions that are not relevant for self-organized workshops, including:

"I understand the Data Carpentry administration fee."
"I would like to submit an administrative fee waiver application."
"My institution will cover instructors' travel and accommodation costs."
"How will instructors' travel and accommodation be managed?"
"Other propositions for managing instructors' travel and accommodations"

I'm not sure whether the "Preferred workshop dates" text box is appropriate either. 

Is there a separate form that should be linking here?

**Comment by ErinBecker** [comment]
Ping @maneesha.

**Comment by ErinBecker** [comment]
Ping @tracykteal - Is this an issue for Piotyr?

**Comment by maneesha** [comment]
Preferred workshop dates - should read just  "Workshop Dates" as they are responsible for schedule it themselves

Approximate number of attendees - we should leave this in but the help text should read  "This number doesn't need to be precise, but will help you decide how many instructors your workshop will need.Each workshop must have at least two instructors."

This: We currently have developed or are developing workshops focused on four types of data. Please let us know which workshop would best suit your needs.
Should read as: We currently have developed or are developing workshops focused on four types of data. Please let us know which workshop you are planning to teach.

Leave this out: How will instructors' travel and accommodations be managed?
as that is up to the organizers to deal with.

These should also be left out:
"I understand the Data Carpentry administration fee."
"I would like to submit an administrative fee waiver application."
"My institution will cover instructors' travel and accommodation costs."
"How will instructors' travel and accommodation be managed?"
"Other propositions for managing instructors' travel and accommodations"

We should just have one check box reading something like:
"I am applying for a waiver to run a self organized Data Carpentry workshop.  I understand I may not proceed with this workshop until the waiver is granted.  I will be notified within [how long -- I'd say two weeks?] of Data Carpentry's decision."
(knowing we will typically notify people in less time than that; this is just the high end)

We should also have a question asking who the instructors and helpers are going to be.

@tracykteal should approve this before we make any changes.

**Comment by ErinBecker** [comment]
Thanks @maneesha. I'll coordinate with @tracykteal and @pbanaszkiewicz about getting this split into two forms.

**Comment by ErinBecker** [comment]
There is an existing form for this, but needs some modifications. See [this PR in amy repo](https://github.com/swcarpentry/amy/issues/967)

**Comment by ErinBecker** [comment]
Closed with https://github.com/swcarpentry/amy/issues/967
