### ISSUE TITLE
Text breaking on Safari and Firefox

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/datacarpentry.github.io#96]
On Safari and Firefox (but not Chrome), text wrapping appears to have a hard character set in that words are being hyphenated rather than moved to next line. Checkout for example the /partnership/ page. This issue appears to be present on both full-width (eg. /partnership/) and half-width (eg. /workshops/) pages and significantly impacts readability on Safari and Firefox.

This is also happening on SWC pages (eg. http://software-carpentry.org/conduct/).

@tracykteal @gvwilson Can you confirm this isn't just me?

**Comment by tracykteal** [comment]
The template default does prefer hyphenation. I worked for a while to fix this, but didn't resolve it. I thought the SWC updates had resolved it though.

**Comment by hlapp** [comment]
Hyphenation is controlled via CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens

If you want to disable hyphenation everywhere, disable it at the `body` element. (By default it is inherited.) Otherwise, disable it for the element for which you don't want it.

**Comment by ErinBecker** [comment]
Thanks @hlapp . I'll try to get the hyphenation disabled.

**Comment by tracykteal** [comment]
I've tried. It's strangely embedded in the CSS. Definitely worth another look though!
